name: 'Fyle PR Action'
description: 'Checks for pull requests'
inputs:
  github-token:
    description: 'GitHub repository token'
    required: true
  config-file:
    description: 'Path to the configuration file'
    required: true
    default: '.github/pr_checks_config.yaml'
runs:
  using: 'docker'
  image: 'fylehq/fyle-pr-action:v1'
  args:
    - ${{ inputs.github-token }}
    - ${{ inputs.config-file }}
